[package]
name = "url-install"
version = "0.1.0"
authors = ["Your Name <you@email.com>"]
edition = "2018"

[dependencies]
reqwest = "0.10.8"
indicatif = "0.9.0"
failure = "0.1.2"
exitfailure = "0.5.1"
tokio = { version = "0.2", features = ["full"] }
http =""